name: auto task

on:
  workflow_dispatch:

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Clean Workflow Runs
        run: |
          echo "Starting total cleanup of all workflows..."
          WORKFLOWS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows" \
            | jq '.workflows[] | .id')

          for wf in $WORKFLOWS; do
            RUN_IDS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$wf/runs?per_page=100" \
              | jq ".workflow_runs[] | select(.id != ${{ github.run_id }}) | .id")

            if [ -z "$RUN_IDS" ]; then
              continue
            fi

            for run_id in $RUN_IDS; do
              echo "Deleting historical run ID: $run_id"
              curl -L -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
            done
          done

          echo "Cleanup completed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
